### PR TITLE
Add support for other projections

### PR DESCRIPTION
**Pull request by gjmooney**
Small fix for issue with the tif layer loading in the wrong location mentioned in #196 Should fix https://github.com/geojupyter/jupytergis/issues/191

fix

Added support for reading projection info from `gqz` files. 

EPSG:3857

EPSG:4326

### CODE REVIEW

**Review by martinRenou — APPROVED** [review]
Neat!

**Comment by gjmooney** [comment]
> Should fix #191

I saved a `qgz` using the aitoff projection, and opening that in Jupyter GIS shows the layer with the default projection, but we still need to implement getting the projection from the QGIS and set that properly in JGIS.  It seems like it should be straight forward enough, `qgz` files have the `proj` string used in `proj.def()` but I was getting some weird webpack errors when I was playing around with it, so maybe not so straight forward :man_shrugging:

**Comment by martinRenou** [comment]
What kind of webpack errors?

**Comment by gjmooney** [comment]
> What kind of webpack errors?

For example, replacing `proj4.defs(Array.from(proj4list))` with `proj4.defs('EPSG:7030, 'aitoff +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs'`
 causes 

error

**Comment by martinRenou** [comment]
Oo that is really weird. I don't understand how this error message can relate to the code being run.

**Comment by gjmooney** [comment]
> Oo that is really weird. I don't understand how this error message can relate to the code being run.

Especially since `proj4.defs(Array.from(proj4list))` works fine! It's bizarre :melting_face:

**Comment by martinRenou** [comment]
It says `qgisplugin failed to activate`. Did you change anything in the plugin implementation?

**Comment by gjmooney** [comment]
> It says `qgisplugin failed to activate`. Did you change anything in the plugin implementation?

Nope, literally just changed that one line.

**Comment by gjmooney** [comment]
> Can you push the diff loading the projection from the qgz file, then share that file?
> 
> I will give it a try locally

I'm not loading from the `qgz` directly yet, I just looked in the extracted `qgz` file to get the  `aitoff +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs` string to create the proj4 def to use for the OpenLayers `Projection`

**Comment by martinRenou** [comment]
Can you try running:

```
proj4.defs('EPSG:7030, 'aitoff +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs');
register(proj4);
```

At the constructor of the view instead of at the top of the file? Wondering if the error message would get more useful that way.

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
