### PR TITLE
Fix shippping of geojson schema

### LINKED ISSUE #235: Cannot open GeoJSON files anymore
Screenshot From 2024-12-10 15-43-19

### PR DESCRIPTION
**Pull request by arjxn-py**
Remove extra dependency and minor improvements

### CODE REVIEW

**Comment by martinRenou** [comment]
I can still reproduce the issue on the lite deployment for this PR:

See https://appsharing.space/static-app?url=https://github.com/geojupyter/jupytergis/actions/runs/12274797031/artifacts/2305136325&indexPath=lite/lab/index.html

Screenshot From 2024-12-11 13-13-29

**Comment by martinRenou** [comment]
It turns out the initial issue is unrelated to this https://github.com/geojupyter/jupytergis/pull/241

But your PR is still a net improvement, thanks!

**Comment by arjxn-py** [comment]
> But your PR is still a net improvement, thanks!

Thanks for suggesting this in the first place :)

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
