### PR TITLE
Update to jupyter-collaboration>=3

### LINKED ISSUE #158: Bump jupyter-collaboration
Port https://github.com/jupytercad/JupyterCAD/pull/429

### PR DESCRIPTION
**Pull request by brichet**
Fixes #158

This PR bumps jupyter-collaboration to the version 3

### CODE REVIEW

**Comment by martinRenou** [comment]
The JupyterLab version was pinned in https://github.com/geojupyter/jupytergis/pull/203 to fix UI tests

**Comment by martinRenou** [comment]
You may need to also update the pins of the Python package in tests (it's done in multiple places) https://github.com/geojupyter/jupytergis/blob/main/.github/workflows/build.yml#L24

**Comment by brichet** [comment]
> You may need to also update the pins of the Python package in tests (it's done in multiple places) https://github.com/geojupyter/jupytergis/blob/main/.github/workflows/build.yml#L24

Not sure to understand, is it something different from #203 ?

**Comment by martinRenou** [comment]
I commented before seeing your latest commit c97c1eb40db2cbea26422cf25d9c261d811e8a7a Looks good1

**Comment by martinRenou** [comment]
Seems to be running fine now 💯 the last failure looks like the one we hit sometimes

**Comment by brichet** [comment]
> Seems to be running fine now 💯 the last failure looks like the one we hit sometimes

Not sure this is the same, but I may have a fix for the current issue. I pushed it in https://github.com/geojupyter/jupytergis/pull/204/commits/45d258880757e5202652457c4f38dcd3c651070a, but this looks like an issue in lab and should be fixed upstream.
The issue is that the toolbar is computed before the document is available, and then the `tracker.currentWidget.context.model.sharedModel.editable`, that is used to enable the buttons in several (all ?) commands, is false.

The fix is to `notifyCommandChanged` (to reload the commands properties)  right after the jupyterGIS widget is created.

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
