### PR TITLE
Add back ShapeFile Support

### LINKED ISSUE #140: Cannot load ShapeFile
Shapefile loading is broken since we've transitioned from `maplibre-gl` to `OpenLayers` to render maps. I personally couldn't find the code to load shapeFile in the new [mainView](https://github.com/geojupyter/jupytergis/blob/main/packages/base/src/mainview/mainView.tsx) component, which results in the following error in the console - 
```
mainView.js:364 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'set')
```

### PR DESCRIPTION
**Pull request by arjxn-py**
Should fix #140 & #117 

https://github.com/user-attachments/assets/48b9cb16-f7e8-40eb-8792-48c3b00b10c5

### CODE REVIEW

**Review by brichet — COMMENTED** [review]
Thanks @arjxn-py, this looks great.

It can be in follow up PR:
- can we add tests on it to prevent it from being broken
- looks like changing the color only affect the border of the shapes. Would it be easy to propagate it to the background also ?

**Comment by arjxn-py** [comment]
Hi @brichet, thanks for the review :)

> can we add tests on it to prevent it from being broken

Sure, I'll be happy to add those, haven't added one to JGIS before so I'd once have to give a look to other tests and PR how they do it.

> looks like changing the color only affect the border of the shapes. Would it be easy to propagate it to the background also ?

Yeah, I notice that too. I'll be happy to look into that as well. On a side note I'll also see if the same is happening for GeoJSON layer too as in the case of ShapeFile too, it is first being converted to GeoJson and then being overlayed on the map. But at the moment i'm quite unsure about the complexity of the same hence if it's easy I'll be sure to fix it directly but in case I couldn't manage to I'll be happy to open an issue for the same to keep track.

**Review by martinRenou — APPROVED** [review]
Thanks @arjxn-py !

**Comment by brichet** [comment]
> But at the moment i'm quite unsure about the complexity of the same hence if it's easy I'll be sure to fix it directly but in case I couldn't manage to I'll be happy to open an issue for the same to keep track.

I was looking at it and you're right, the issue is the same for the GeoJSON layer. 
It has to be fixed for the `VectorLayer`, I think probably at https://github.com/geojupyter/jupytergis/blob/7cf2425b6e05015f438aa8a4f6346c446addb474/packages/base/src/mainview/mainView.tsx#L555

**Comment by arjxn-py** [comment]
> > But at the moment i'm quite unsure about the complexity of the same hence if it's easy I'll be sure to fix it directly but in case I couldn't manage to I'll be happy to open an issue for the same to keep track.
> 
> I was looking at it and you're right, the issue is the same for the GeoJSON layer. It has to be fixed for the `VectorLayer`, I think probably at
> 
> https://github.com/geojupyter/jupytergis/blob/7cf2425b6e05015f438aa8a4f6346c446addb474/packages/base/src/mainview/mainView.tsx#L555

Thanks for looking into it already 🚀, this is helpful. I'll be happy to make a quick try on it to see if it can be fixed easily.

**Pull request merged**
